# Taken from LyricFind.com
# Lyrics by andrew taggart, chris martin,
# guy berryman, johnny buckland, will champion
# Sung by Coldplay and Chainsmokers
print("I've been reading books of old")
print("The legends and the myths")
print("Achilles and his gold")
print("Hercules and his gifts")
print("Spiderman's control")
print("And Batman with his fists")
print("And clearly I don't see myself upon that list")
print("But she said, 'where'd you wanna go?'")
print("How much you wanna risk?")
print("I'm not looking for somebody")
print("With some superhuman gifts")
print("Some superhero")
print("Some fairytale bliss")
print("Just something I can turn to")
print("Somebody I can kiss")
print("I want something just like this")
print("Oh, I want something just like this")
print("Oh, I want something just like this")
print("Oh, I want something just like this")
print("Oh, I've been reading books of old")
print("The legends and the myths")
print("The testaments they told")
print("The moon and its eclipse")
print("And Superman unrolls")
print("A suit before he lifts")
print("But I'm not the kind of person that it fits")
print("She said, 'Where'd you wanna go?'")
print("How much you wanna risk?")
print("I'm not looking for somebody")
print("With some superhuman gifts")
print("Some superhero")
print("Some fairytale bliss")
print("Just something I can turn to")
print("Somebody I can miss")
print("I want something just like this")
print("I want something just like this")
print("Oh, I want something just like this")
print("Oh, I want something just like this")
print("Where'd you wanna go?")
print("How much you wanna risk?")
print("I'm not looking for somebody")
print("With some superhuman gifts")
print("Some superhero")
print("Some fairytale bliss")
print("Just something I can turn to")
print("Somebody I can kiss")
print("I want something just like this")
print("Oh, I want something just like this")
print("Oh, I want something just like this")
print("Oh, I want something just like this")
